// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitInfo = { branch: string | null, isDirty: boolean, ahead: number, behind: number, };
