// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitDirection } from "./SplitDirection";

export type LayoutNode = { "type": "leaf", paneId: string, } | { "type": "split", direction: SplitDirection, children: [LayoutNode, LayoutNode], sizes: [number, number], };
