// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneType } from "./PaneType";

export type PaneInfo = { id: string, ptyId: string, paneType: PaneType, cwd: string | null, };
