// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";

export type SurfaceInfo = { id: string, name: string, layout: LayoutNode, };
