// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceInfo } from "./SurfaceInfo";

export type WorkspaceInfo = { id: string, name: string, projectId: string, worktreePath: string, branchName: string | null, isRootWorktree: boolean, surfaces: Array<SurfaceInfo>, activeSurfaceIndex: number, createdAt: bigint, };
