// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PtyConfig = { shell: string | null, cwd: string | null, env: { [key in string]?: string } | null, rows: number | null, cols: number | null, };
